### ISSUE TITLE
Changing directory to a git repo does not show branch name immediately

### ISSUE THREAD

**Issue by nan0tube** [jorgebucaran/hydro#12]
The branch name does not appear upon `cd` into the repo, but on subsequent commands.

```
~ ❱ git clone https://github.com/jorgebucaran/hydro.git
Cloning into 'hydro'...
remote: Enumerating objects: 403, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 403 (delta 0), reused 1 (delta 0), pack-reused 400
Receiving objects: 100% (403/403), 108.71 KiB | 283.00 KiB/s, done.
Resolving deltas: 100% (199/199), done.
~ 1.5s ❱ cd hydro/
~/hydro ❱ fish -v
fish, version 3.1.0
~/hydro main ❱ fisher list 
jorgebucaran/fisher
jethrokuan/z
jethrokuan/fzf
jorgebucaran/hydro
~/hydro main ❱ 
```

**Comment by jorgebucaran** [comment]
Could be a problem with Fish 3.1.0. Not entirely sure. Could you upgrade to the latest version of Fish? There's rarely any reason to not be running the latest Fish. If you're on macOS, `brew` is your friend. If you're using a rolling release distro, you already got the latest cut. Otherwise, the official Fish PPA always has the latest version.

If you still encounter the same issue after upgrading Fish, then reopen so we can look into it.

**Comment by nan0tube** [comment]
Thanks for the tip, this is no longer an issue upon upgrade to the latest fish (3.2.2) via the official PPA.
